import 'package:flutter/material.dart';
import 'package:foodly/models/food_category.dart';

import 'food_item.dart';

class Restaurant {
  List<FoodCategory> categories = [
    FoodCategory(title: "Protein", foodItems: [
      FoodItem(
        name: "Roast Beef",
        foodKind: "Protein",
        price: 23.8,
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        imagePath: "assets/images/roastbeef.jpg",
        shippingPrice: 9,
        shippingAddress: "Gaza Strip",
        review: 5.0,
        preparationTime: "10 min",
        description: "Roast beef is a dish of beef that is roasted, generally served as the main dish of a meal.",
      ),
      FoodItem(
        name: "Chicken Breasts",
        foodKind: "Protein",
        price: 25.8,
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        imagePath: "assets/images/chicken-breasts.jpg",
        shippingPrice: 11,
        shippingAddress: "Gaza Strip",
        review: 4.6,
        preparationTime: "10 min",
        description: "Chicken is the most common type of poultry in the world.",
      ),
    ]),
    FoodCategory(title: "Seafood", foodItems: [
      FoodItem(
        name: "Oyster Dish",
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        foodKind: "Seafood",
        price: 12.98,
        imagePath: "assets/images/oyster-dish.png",
        shippingPrice: 14,
        shippingAddress: "Gaza Strip",
        review: 4.5,
        preparationTime: "15 min",
        description: "Shortbread, chocolate turtle cookies, and red velvet.",
      ),
      FoodItem(
        name: "Oyster On Ice",
        foodKind: "Seafood",
        price: 7.4,
        imagePath: "assets/images/oyster-on-ice.png",
        shippingPrice: 14,
        shippingAddress: "Gaza Strip",
        review: 4.1,
        preparationTime: "12 min",
        description: "Shortbread, chocolate turtle cookies, and red velvet.",
      ),
      FoodItem(
        name: "Fried Rice on Pot",
        foodKind: "Seafood",
        price: 15.6,
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        imagePath: "assets/images/fried-rice-on-pot.png",
        shippingPrice: 14,
        shippingAddress: "Gaza Strip",
        review: 4.9,
        preparationTime: "10 min",
        description: "Shortbread, chocolate turtle cookies, and red velvet.",
      ),
      FoodItem(
        name: "Shrip Dish",
        foodKind: "Seafood",
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        price: 18.6,
        imagePath: "assets/images/shrip-dish.png",
        shippingPrice: 10,
        shippingAddress: "Gaza Strip",
        review: 3.9,
        preparationTime: "13 min",
        description: "Shortbread, chocolate turtle cookies, and red velvet.",
      ),
    ]),
    FoodCategory(title: "Appetizers", foodItems: [
      FoodItem(
        name: "French Fries",
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        foodKind: "Appetizers",
        price: 14.6,
        imagePath: "assets/images/french-fries.jpg",
        shippingPrice: 8,
        shippingAddress: "French",
        review: 4.7,
        preparationTime: "9 min",
        description: "simply fries, are batonnet, possibly originating from France.",
      ),
      FoodItem(
        name: "Stuffed Mushrooms",
        foodKind: "Appetizers",
        price: 12.6,
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        imagePath: "assets/images/stuffed-mushrooms.jpg",
        shippingPrice: 7,
        shippingAddress: "French",
        review: 3.7,
        preparationTime: "6 min",
        description: "Stuffed mushrooms is a dish prepared using edible mushrooms as its primary ingredient.",
      ),
    ]),
    FoodCategory(title: "Drinks", foodItems: []),
    FoodCategory(title: "Fruit & Vegetables", foodItems: [
      FoodItem(
        name: "Fruit Salad",
        foodKind: "Fruit & Vegetables",
        price: 13.8,
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        imagePath: "assets/images/fruit-salad.jpg",
        shippingPrice: 4,
        shippingAddress: "French",
        review: 4.7,
        preparationTime: "1 min",
        description: "Fruit salad is a dish consisting of various kinds of fruit",
      ),
      FoodItem(
        name: "Lychee",
        additions: const [
          "Chocolate Chip",
          "Cookies and Cream",
          "Funafuti",
          "M and M",
          "Red Velvet",
          "Peanut Butter",
          "Snickers's",
          "White Chocolate Macadamia",
        ],
        foodKind: "Fruit & Vegetables",
        price: 14.8,
        imagePath: "assets/images/lychee.jpg",
        shippingPrice: 9,
        shippingAddress: "French",
        review: 1.7,
        preparationTime: "1 min",
        description: "Lychee is a monotypic taxon and the sole member in the genus Litchi in the soapberry family.",
      ),
    ]),
  ];

  List<FoodItem> mostPopular = [
    FoodItem(
      imagePath: "assets/images/cookie-sandwich.png",
      name: "Cookie Sandwich",
      preparationTime: "15 min",
      shippingAddress: "North Beach, San Francisco",
      review: 5.0,
      additions: const [
        "Chocolate Chip",
        "Cookies and Cream",
        "Funafuti",
        "M and M",
        "Red Velvet",
        "Peanut Butter",
        "Snickers's",
        "White Chocolate Macadamia",
      ],
      foodKind: "American",
      shippingPrice: 15,
      price: 35,
    ),
    FoodItem(
      imagePath: "assets/images/chow-fun.png",
      name: "Chow Fun",
      preparationTime: "15 min",
      shippingAddress: "North Beach, San Francisco",
      review: 5.0,
      additions: const [
        "Chocolate Chip",
        "Cookies and Cream",
        "Funafuti",
        "M and M",
        "Red Velvet",
        "Peanut Butter",
        "Snickers's",
        "White Chocolate Macadamia",
      ],
      foodKind: "Chinese",
      shippingPrice: 15,
      price: 20,
    ),
    FoodItem(
      imagePath: "assets/images/dim-sum-combo.png",
      name: "Dim Sum Combo",
      preparationTime: "15 min",
      shippingAddress: "North Beach, San Francisco",
      review: 5.0,
      additions: const [
        "Chocolate Chip",
        "Cookies and Cream",
        "Funafuti",
        "M and M",
        "Red Velvet",
        "Peanut Butter",
        "Snickers's",
        "White Chocolate Macadamia",
      ],
      foodKind: "Chinese",
      shippingPrice: 15,
      price: 49,
    ),
  ];

  List<FoodItem> featuredItems = [
    FoodItem(
      imagePath: "assets/images/cookie-sandwich.png",
      name: "Cookie Sandwich",
      preparationTime: "15 min",
      shippingAddress: "North Beach, San Francisco",
      review: 5.0,
      additions: const [
        "Chocolate Chip",
        "Cookies and Cream",
        "Funafuti",
        "M and M",
        "Red Velvet",
        "Peanut Butter",
        "Snickers's",
        "White Chocolate Macadamia",
      ],
      foodKind: "American",
      shippingPrice: 15,
      price: 35,
    ),
    FoodItem(
      imagePath: "assets/images/chow-fun.png",
      name: "Chow Fun",
      preparationTime: "15 min",
      shippingAddress: "North Beach, San Francisco",
      review: 5.0,
      additions: const [
        "Chocolate Chip",
        "Cookies and Cream",
        "Funafuti",
        "M and M",
        "Red Velvet",
        "Peanut Butter",
        "Snickers's",
        "White Chocolate Macadamia",
      ],
      foodKind: "Chinese",
      shippingPrice: 15,
      price: 20,
    ),
    FoodItem(
      imagePath: "assets/images/dim-sum-combo.png",
      name: "Dim Sum Combo",
      preparationTime: "15 min",
      shippingAddress: "North Beach, San Francisco",
      review: 5.0,
      additions: const [
        "Chocolate Chip",
        "Cookies and Cream",
        "Funafuti",
        "M and M",
        "Red Velvet",
        "Peanut Butter",
        "Snickers's",
        "White Chocolate Macadamia",
      ],
      foodKind: "Chinese",
      shippingPrice: 15,
      price: 49,
    ),
  ];

  List<String> mealsImages;
  String name, preparingAverageTime;
  List<String> foodKinds;
  double reviewingAverage, shippingPrice;
  int numberOfReviews;
  int currentImageIndex = 0;
  PageController pageController = PageController();

  Restaurant(
      {required this.mealsImages,
      required this.name,
      required this.foodKinds,
      required this.numberOfReviews,
      required this.reviewingAverage,
      required this.preparingAverageTime,
      required this.shippingPrice});
}
